apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-udm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-udm.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-udm.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 2 }}
      initContainers:
      {{- if .Values.start.proxy }}
      - name: init-networking
        image: tolgaomeratalay/init-networking:v5
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
    {{- end }}
      containers:
      - name: proxy
        image: "{{ .Values.proxyimage.repository }}:{{ .Values.proxyimage.version }}"
        imagePullPolicy: {{ .Values.proxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11095
        env:
        - name: SA_NAME
          value: {{ .Values.proxyconfig.saname | quote }}
        - name: SA_SUB_FUNC
          value: {{ .Values.proxyconfig.sasubfunc | quote }}
        - name: SA_IP
          value: {{ .Values.proxyconfig.saip | quote }}
        - name: SA_LOC
          value: {{ .Values.proxyconfig.saloc | quote }}
        - name: SA_K8S_DNS
          value: {{ .Values.proxyconfig.sak8sdns | quote }}
        - name: SA_VNF_TYPE
          value: {{ .Values.proxyconfig.savnftype | quote }}
        - name: SA_VNF_ID
          value: {{ .Values.proxyconfig.savnfid | quote }}
        - name: SA_SLICE_ID
          value: {{ .Values.proxyconfig.sasliceid | quote }}
        - name: STREAM_SCP_IP
          value: {{ .Values.proxyconfig.streamscpip | quote }}
        - name: STREAM_SCP_PORT
          value: {{ .Values.proxyconfig.streamscpport | quote }}
        - name: RANDOMIZE
          value: {{ .Values.proxyconfig.randomize | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.proxyconfig.loglevel | quote }}
        - name: CLIENT_COUNT
          value: {{ .Values.proxyconfig.clientcount | quote }}
        - name: MULTI_REG
          value: {{ .Values.proxyconfig.multireg | quote }}
        - name: OPERATION_MODE
          value: {{ .Values.proxyconfig.operationmode | quote }}
        - name: VAL_METHOD
          value: {{ .Values.proxyconfig.valmethod | quote }}
        - name: USE_OTEL
          value: {{ .Values.proxyconfig.useotel | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{- if not .Values.start.proxy }}
        command:
          - /bin/sleep
          - infinity
        {{- end }}
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
         {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/oai-udm_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.sharedvolume}}
        volumeMounts:
        - mountPath: "/pcap"
          name: cn5g-pv
        {{- end}}
      - name: udm
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        imagePullPolicy: {{ .Values.nfimage.pullPolicy }}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tz     
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: UDM_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udmName
          - name: SBI_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiIfName
          - name: SBI_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp1
          - name: SBI_HTTP2_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp2
          - name: UDM_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udmApiVersionNb
          - name: USE_FQDN_DNS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: useFqdnDns
          - name: UDR_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrIpAddress
          - name: UDR_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrPort
          - name: UDR_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrApiVersionNb
          - name: UDR_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrFqdn
          - name: NRF_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfIpAddress
          - name: NRF_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfPort
          - name: NRF_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfApiVersionNb
          - name: NRF_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfFqdn
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.nf.requests.memory | quote }}
            cpu: {{ .Values.resources.nf.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.nf.limits.memory | quote }}
            cpu: {{ .Values.resources.nf.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.config.sbiPortHttp1 }}
          name: http1
        - containerPort: {{ .Values.config.sbiPortHttp2 }}
          name: http2
        {{- if .Values.start.udm}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.start.udm}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
      volumes:
      {{- if .Values.persistence.sharedvolume}}
      - name: cn5g-pv
        persistenceVolumeClaim:
          claimName: cn5g-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
