apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-nrf.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-nrf.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-nrf.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 2 }}
      initContainers:
      {{- if .Values.start.proxy }}
      - name: init-networking
        image: tolgaomeratalay/init-networking:v5
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
    {{- end }}
      containers:
      - name: proxy
        image: "{{ .Values.proxyimage.repository }}:{{ .Values.proxyimage.version }}"
        imagePullPolicy: {{ .Values.proxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11095
        env:
        - name: SA_NAME
          value: {{ .Values.proxyconfig.saname | quote }}
        - name: SA_SUB_FUNC
          value: {{ .Values.proxyconfig.sasubfunc | quote }}
        - name: SA_IP
          value: {{ .Values.proxyconfig.saip | quote }}
        - name: SA_LOC
          value: {{ .Values.proxyconfig.saloc | quote }}
        - name: SA_K8S_DNS
          value: {{ .Values.proxyconfig.sak8sdns | quote }}
        - name: SA_VNF_TYPE
          value: {{ .Values.proxyconfig.savnftype | quote }}
        - name: SA_VNF_ID
          value: {{ .Values.proxyconfig.savnfid | quote }}
        - name: SA_SLICE_ID
          value: {{ .Values.proxyconfig.sasliceid | quote }}
        - name: STREAM_SCP_IP
          value: {{ .Values.proxyconfig.streamscpip | quote }}
        - name: STREAM_SCP_PORT
          value: {{ .Values.proxyconfig.streamscpport | quote }}
        - name: RANDOMIZE
          value: {{ .Values.proxyconfig.randomize | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.proxyconfig.loglevel | quote }}
        - name: CLIENT_COUNT
          value: {{ .Values.proxyconfig.clientcount | quote }}
        - name: MULTI_REG
          value: {{ .Values.proxyconfig.multireg | quote }}
        - name: OPERATION_MODE
          value: {{ .Values.proxyconfig.operationmode | quote }}
        - name: VAL_METHOD
          value: {{ .Values.proxyconfig.valmethod | quote }}
        - name: USE_OTEL
          value: {{ .Values.proxyconfig.useotel | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        {{- if not .Values.start.proxy }}
          - /bin/sleep
          - infinity
        {{- end }}
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/{{ .Chart.Name }}_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistent.sharedvolume}}
        volumeMounts:
        - mountPath: "/pcap"
          name: cn5g-pvc
        {{- end}}
      - name: nrf
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        imagePullPolicy: {{ .Values.nfimage.pullPolicy }}
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.nf.requests.memory | quote }}
            cpu: {{ .Values.resources.nf.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.nf.limits.memory | quote }}
            cpu: {{ .Values.resources.nf.limits.cpu | quote }}
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-nrf/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-nrf/bin/healthcheck.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        {{- end}}
        ports:
        - containerPort: {{ .Values.config.nrfInterfacePortForSBI }}
          name: http1
          protocol: TCP
        - containerPort: {{ .Values.config.nrfInterfaceHttp2PortForSBI }}
          name: http2
          protocol: TCP
        env:
          - name: NRF_INTERFACE_NAME_FOR_SBI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfInterfaceNameForSBI
          - name: NRF_INTERFACE_PORT_FOR_SBI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfInterfacePortForSBI
          - name: NRF_INTERFACE_HTTP2_PORT_FOR_SBI
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfInterfaceHttp2PortForSBI
          - name: NRF_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfApiVersion
      volumes:
      {{- if .Values.persistent.sharedvolume}}
      - name: cn5g-pvc
        persistentVolumeClaim:
          claimName: cn5g-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
