apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-udm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "oai-udm.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-udm.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-ndn-net
    spec:
      nodeSelector:
      {{ toYaml .Values.nodeSelector | indent 2 }}
      initContainers:
      {{- if .Values.start.startproxy }}
      - name: init-networking
        image: "{{ .Values.initimage.repository }}:{{ .Values.initimage.initversion }}"
        imagePullPolicy: {{ .Values.initimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        env:
        - name: OPERATION_MODE
          value: {{ .Values.biproxy.opmode | quote }}
        - name: PACKET_LOSS_RATE
          value: {{ .Values.biproxy.packetloss | quote }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
    {{- end }}
      containers:
      {{- if .Values.start.startndnproxy }}
      - name: htoi
        image: "{{ .Values.ndnproxyimage.repository }}:{{ .Values.ndnproxyimage.ndnpversion }}"
        imagePullPolicy: {{ .Values.ndnproxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11099
        env:
        - name: LOG_LEVEL
          value: {{ .Values.ndnproxy.loglevel | quote }}
        - name: THREAD_COUNT
          value: {{ .Values.ndnproxy.threadcount | quote }}
        - name: NFD_SERVER_IP
          value: {{ .Values.ndnproxy.nfdserverip | quote }}
        - name: NDN_PREFIXES
          value: {{ .Values.ndnproxy.ndnprefixes | quote }}
        - name: MODE
          value: {{ .Values.ndnproxy.htoimode | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #command:
        #  - /bin/sleep
        #  - infinity
      {{- end }}
      {{- if .Values.start.startndnproxy }}
      - name: itoh
        image: "{{ .Values.ndnproxyimage.repository }}:{{ .Values.ndnproxyimage.ndnpversion }}"
        imagePullPolicy: {{ .Values.ndnproxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11099
        env:
        - name: LOG_LEVEL
          value: {{ .Values.ndnproxy.loglevel | quote }}
        - name: THREAD_COUNT
          value: {{ .Values.ndnproxy.threadcount | quote }}
        - name: NFD_SERVER_IP
          value: {{ .Values.ndnproxy.nfdserverip | quote }}
        - name: NDN_PREFIXES
          value: {{ .Values.ndnproxy.ndnprefixes | quote }}
        - name: MODE
          value: {{ .Values.ndnproxy.itohmode | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        #  - /bin/sleep
        #  - infinity
      {{- end }}
      {{- if .Values.start.startbiproxy }}
      - name: proxy
        image: "{{ .Values.proxyimage.repository }}:{{ .Values.proxyimage.saversion }}"
        imagePullPolicy: {{ .Values.proxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11095
        env:
        - name: LOG_LEVEL
          value: {{ .Values.biproxy.loglevel | quote }}
        - name: OPERATION_MODE
          value: {{ .Values.biproxy.opmode | quote }}
        - name: USE_TLS
          value: {{ .Values.biproxy.http1tls | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        #  - /bin/sleep
        #  - infinity
                                                                                               128,1         25%
        imagePullPolicy: {{ .Values.initimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        env:
        - name: OPERATION_MODE
          value: {{ .Values.biproxy.opmode | quote }}
        - name: PACKET_LOSS_RATE
          value: {{ .Values.biproxy.packetloss | quote }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
    {{- end }}
      containers:
      {{- if .Values.start.startndnproxy }}
      - name: htoi
        image: "{{ .Values.ndnproxyimage.repository }}:{{ .Values.ndnproxyimage.ndnpversion }}"
        imagePullPolicy: {{ .Values.ndnproxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11099
        env:
        - name: LOG_LEVEL
          value: {{ .Values.ndnproxy.loglevel | quote }}
        - name: THREAD_COUNT
          value: {{ .Values.ndnproxy.threadcount | quote }}
        - name: NFD_SERVER_IP
          value: {{ .Values.ndnproxy.nfdserverip | quote }}
        - name: NDN_PREFIXES
          value: {{ .Values.ndnproxy.ndnprefixes | quote }}
        - name: MODE
          value: {{ .Values.ndnproxy.htoimode | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #command:
        #  - /bin/sleep
        #  - infinity
      {{- end }}
      {{- if .Values.start.startndnproxy }}
      - name: itoh
        image: "{{ .Values.ndnproxyimage.repository }}:{{ .Values.ndnproxyimage.ndnpversion }}"
        imagePullPolicy: {{ .Values.ndnproxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11099
        env:
        - name: LOG_LEVEL
          value: {{ .Values.ndnproxy.loglevel | quote }}
        - name: THREAD_COUNT
          value: {{ .Values.ndnproxy.threadcount | quote }}
        - name: NFD_SERVER_IP
          value: {{ .Values.ndnproxy.nfdserverip | quote }}
        - name: NDN_PREFIXES
          value: {{ .Values.ndnproxy.ndnprefixes | quote }}
        - name: MODE
          value: {{ .Values.ndnproxy.itohmode | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        #  - /bin/sleep
        #  - infinity
      {{- end }}
      {{- if .Values.start.startbiproxy }}
      - name: proxy
        image: "{{ .Values.proxyimage.repository }}:{{ .Values.proxyimage.saversion }}"
        imagePullPolicy: {{ .Values.proxyimage.pullPolicy }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        ports:
        - containerPort: 11095
        env:
        - name: LOG_LEVEL
          value: {{ .Values.biproxy.loglevel | quote }}
        - name: OPERATION_MODE
          value: {{ .Values.biproxy.opmode | quote }}
        - name: USE_TLS
          value: {{ .Values.biproxy.http1tls | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        #  - /bin/sleep
        #  - infinity
      {{- end }}
      - name: tcpdump
        image: "{{ .Values.tcpdumpimage.repository }}:{{ .Values.tcpdumpimage.version }}"
        imagePullPolicy: {{ .Values.tcpdumpimage.pullPolicy }}
         {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.tcpdump.requests.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.tcpdump.limits.memory | quote }}
            cpu: {{ .Values.resources.tcpdump.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.start.tcpdump}}
        command:
          - /bin/sh
          - -c
          - /usr/sbin/tcpdump -i any -w /pcap/oai-udm_`date +%Y-%m-%d_%H_%M-%S-%Z`.pcap
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.persistence.sharedvolume}}
        volumeMounts:
        - mountPath: "/pcap"
          name: cn5g-pv
        {{- end}}
      - name: udm
        image: "{{ .Values.nfimage.repository }}:{{ .Values.nfimage.version }}"
        imagePullPolicy: {{ .Values.nfimage.pullPolicy }}
        env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tz     
          - name: INSTANCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: instance
          - name: PID_DIRECTORY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pidDirectory
          - name: UDM_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udmName
          - name: SBI_IF_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiIfName
          - name: SBI_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp1
          - name: SBI_HTTP2_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sbiPortHttp2
          - name: UDM_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udmApiVersionNb
          - name: USE_FQDN_DNS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: useFqdnDns
          - name: UDR_IP_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrIpAddress
          - name: UDR_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrPort
          - name: UDR_VERSION_NB
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrApiVersionNb
          - name: UDR_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: udrFqdn
          - name: NRF_IPV4_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfIpAddress
          - name: NRF_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfPort
          - name: NRF_API_VERSION
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfApiVersionNb
          - name: NRF_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrfFqdn
        {{- if .Values.resources.define}}
        resources:
          requests:
            memory: {{ .Values.resources.nf.requests.memory | quote }}
            cpu: {{ .Values.resources.nf.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.nf.limits.memory | quote }}
            cpu: {{ .Values.resources.nf.limits.cpu | quote }}
        {{- end}}
        {{- if .Values.readinessProbe}}
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 2
          periodSeconds: 3
        {{- end}}
        {{- if .Values.livenessProbe}}
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /openair-udm/bin/healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end}}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.config.sbiPortHttp1 }}
          name: http1
        - containerPort: {{ .Values.config.sbiPortHttp2 }}
          name: http2
        {{- if .Values.start.udm}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
        {{- if .Values.start.udm}}
        {{- else}}
        command:
          - /bin/sleep
          - infinity
        {{- end}}
      volumes:
      {{- if .Values.persistence.sharedvolume}}
      - name: cn5g-pv
        persistenceVolumeClaim:
          claimName: cn5g-pvc
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.svcname }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.nodeSelector}}
      nodeSelector: 
         {{- toYaml .Values.nodeSelector | nindent 12 }}
      {{- end }}
      {{- if .Values.nodeName}}
      nodeName: {{ .Values.nodeName }}
      {{- end }}
