---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-net1
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno2np1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.nupfIP1 "/" .Values.multus.nupfIP1netmask | nospace | quote }},
                        "gateway": {{- cat .Values.multus.nupfIP1Gw | nospace | quote }}
                }
        ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-net2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno2np1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": {{- cat .Values.multus.nupfIP2 "/" .Values.multus.nupfIP2netmask | nospace | quote }},
                        "gateway": {{- cat .Values.multus.nupfIP2Gw | nospace | quote }}
                }
        ]
      }
    }'

