apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnbsim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-gnbsim.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-gnbsim.selectorLabels" . | nindent 8 }}
#      annotations:
#        k8s.v1.cni.cncf.io/networks: {{ .Chart.Name }}-{{ .Values.namespace }}-ngap-net1, {{ .Chart.Name }}-{{ .Values.namespace }}-gtp-net2
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: gnbsim
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.service.http1Port }}
          name: http1
          protocol: TCP
        env:
          - name: MCC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mcc
          - name: MNC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: mnc
          - name: GNBID
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gnbid
          - name: TAC
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: tac
          - name: SST
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sst
          - name: SD
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: sd
          - name: PagingDRX
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: pagingdrx
          - name: RANUENGAPID
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: ranuengapid
          - name: IMEISV
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: imeisv
          - name: MSIN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: msin
          - name: RoutingIndicator
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: routingindicator
          - name: ProtectionScheme
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: protectionscheme
          - name: KEY
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: key
          - name: OPc
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: opc
          - name: DNN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: dnn
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: url
          - name: NRCellID
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: nrcellid
          - name: NGAPPeerAddr
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: ngappeeraddr
          - name: GTPuLocalAddr
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gtpulocaladdr
          - name: GTPuIFname
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: gtpuifname
          - name: USE_FQDN
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: usefqdn
          - name: DEREG_AFTER
            valueFrom:
              configMapKeyRef:
                name: {{ .Chart.Name }}-configmap
                key: deregafter
#        command: ["/bin/bash","-c"]
#        args: ["sleep infinity"]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 15
      #nodeName: perse.5glab.nsa.eurecom.fr

