replicaCount: 1

namespace: "oaicicd-tmp"

image:
  registry: local
  repository: tolgaomeratalay/gnbsim
  version: n4kul
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "oai-gnbsim-sa12"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true

service:
  type: ClusterIP
  http1Port: 80

start:
  gnbsim: true

multus:
  ngapIPadd: "10.100.19.12"
  ngapNetmask: "16"
  ngapGateway: "10.100.10.1"
  gtpIPadd: "10.100.20.12"
  gtpNetmask: "16"
  gtpGateway: "10.100.10.1"
config:
  mcc: "208"
  mnc: "95"
  gnbid: "12"
  tac: "0x00a000"
  sst: "222"
  sd: "00007b"
  pagingdrx: "v32"
  ranuengapid: "0"
  imeisv: "35609204079514"
  msin: "0000000012"
  routingindicator: "1234"
  protectionscheme: "null"
  key: "0C0A34601D4F07677303652C04625312"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  dnn: "default"
  url: "http://10.100.25.10:8000"
  nrcellid: "1"
  ngappeeraddr: "10.100.15.10"
  gtpulocaladdr: "10.100.19.12"
  gtpuifname: "net1"
  usefqdn: "no"
  deregafter: "360000"
persistence:
  enabled: false

resources: 
  requests:
    cpu: 300m
    memory: 2560Mi

nodeSelector: {}

tolerations: []

affinity: {}
