replicaCount: 1

namespace: "oaicicd-tmp"

image:
  registry: local
  repository: tolgaomeratalay/gnbsim
  version: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "oai-gnbsim-sa10"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true

service:
  type: ClusterIP
  http1Port: 80

start:
  gnbsim: true

multus:
  ngapIPadd: "192.100.19.10"
  ngapNetmask: "16"
  ngapGateway: "192.100.10.1"
  gtpIPadd: "192.100.20.10"
  gtpNetmask: "16"
  gtpGateway: "192.100.10.1"

config:
  mcc: "208"
  mnc: "95"
  gnbid: "10"
  tac: "0x00a000"
  sst: "222"
  sd: "00007b"
  pagingdrx: "v32"
  ranuengapid: "0"
  imeisv: "35609204079514"
  msin: "1000000010"
  routingindicator: "1234"
  protectionscheme: "null"
  key: "0C1A34601D4F07677303652C04625010"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  dnn: "default"
  url: "http://192.100.76.205:8000"
  nrcellid: "1"
  ngappeeraddr: "192.100.15.10"
  gtpulocaladdr: "192.100.19.10"
  gtpuifname: "net2"
  usefqdn: "no"
persistence:
  enabled: false

resources: 
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
