apiVersion: v1
name: oai-udm10 
description: Helm chart for UDM network function

type: application

icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png

version: 1.1.2

appVersion: 1.1.2

keywords:
  - 5GCN
  - UDM

sources:
  - https://gitlab.eurecom.fr/oai/cn5g/oai-cn5g-udm

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org
