---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: dnn-net60
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens3",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "10.100.25.60/16",
                        "gateway": "10.100.10.1"
                }
        ]
      }
    }'
