---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition 
metadata:
  name: dnn-net1 
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno2np1",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [
                {
                        "address": "192.100.25.10/16",
                        "gateway": "192.100.10.1"
                }
        ]
      }
    }'
